### ISSUE TITLE
are phases accurately measured?

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#15]
Biil: any comment on how we know developers found the right root cause phase of a defect
- I was concerned that there appears to be no assessment done if
  developers can accurately determine the phase when defect was
  injected.

(Actually, I don't even get this comment... how does anyone find the origin phase  acurrately? boehm? anyone? why are we being pinged on this issue?)

Ignore this: support comment
- In Figure 10, there are many cells missing, for example, no defects
  from planning found in system test, integration test, or acceptance
  test. This suggests that some of the cells may come predominantly
  from one set of projects while others from a different set.

**Comment by WilliamNichols** [comment]
The developers will not be perfect on the injection phases, however,
1) they have been trained in the PSP to make the judgement,
2) this is, more or less, always the problem regardless of the dataset, 
3) if they use the the TSP process, they will analyze their data in the PM to make improvements. 
a)they are motivated to get it right (more or less), and
b) they have a feedback mechanism from the actions.

The main source of inconsistency is likely to be Planning injections. Since the options do not provide a clear "legacy" category, there is likely to be some inconsistency between assigning a defect to "requirements", "legacy", and "planning". The thinking for calling it a planning defect would be, "that was what we planned"
