### ISSUE TITLE
any information on project size?

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#16]
The characteristics of the projects are given in duration and
number of people: no indication of size.

**Comment by llayman** [comment]
None of the data I have shows anything about project size. It's possible it is in the SEMPR_fact_sheets_2014-10-14, but I need the password to unlock the sheet.

It is also possible that Bill knows the answer to this already.

**Comment by llayman** [comment]
@WilliamNichols Do you know if there is project information hidden in the SEMPR fact sheets? If so, can you share either the password for the sheet or the data? Thanks!

**Comment by WilliamNichols** [comment]
We can get project size in several ways
1) duration
2) number of people
3) task hours logged
4) product size (usually in LOC)

The size reporting is inconsistent, 1,2, and 3 are very reliable. I think I gave you a Project_facts along with the logs. THis summarizes the number of people, duration and task hours. Similar information can be extracted from the Time Log or Task log using the Person_Key, effort_in_mintues, and time_stamps. I have older distributions, but I am not sure I ever compiled for this particular dataset. 

I am in the process of updating the project fact sheet (to be used to evaluate some Mexican projects), once complete producing ranges is a small matter of processing in R, Minitab, or an excel worksheet. 
Proceed if you like, or wait a few days and I will give you an updated project_fact_sheet with the summaries

**Comment by WilliamNichols** [comment]
I’m not yet used to Githum, what do I need to do  to push this

**Comment by timm** [comment]
dont need to push...  just dump text into the comments.  note that these comments support markdown (so you can do some styling as you go, if your want(

**Comment by timm** [comment]
@WilliamNichols 
Bill! need your input on this point please. -- @timm

**Comment by WilliamNichols** [comment]
I thought I sent that information already. I tried to post a current version of the Project Fact sheet which has a project number along with some demographic data such as numbers of developers, product size, duration, and so forth.  This is in the Project_Fact_sheet. but I have a newer version. This includes more projects, but the project ID for the ones in the current study have not changed.

**Comment by WilliamNichols** [comment]
OK, since my prior attempt clearly did not work,  I decided to clone the repository and push a csv file
project_process_fidelity_sheet_2015-08-01.csv

This has 394 projects or project cycles, but the project IDs are identical to the earlier version .

the first 15 columns of the header row are
project_key	process_name 	start_date_char	end_date_char	team_size	planAM	actualAM	plan_duration_weeks	actual_duration_weeks	plan_duration_days	actual_duration_days	duration_variance_schedule_days	duration_variance_schedule_percent	plan_task_hours actual_task_hours


This provides all the necessary information about project size measured in several different ways. I also have some partially completed work on joining related projects, but that is beyond the scope of what we can address in a paper this short. 

Is there anything else you need.

Plan/Actual AM are added and modified LOC

**Comment by WilliamNichols** [comment]
OK, since my prior attempt clearly did not work, I decided to clone the repository and push a csv file
project_process_fidelity_sheet_2015-08-01.csv

This has 394 projects or project cycles, but the project IDs are identical to the earlier version .

the first 15 columns of the header row are
project_key process_name start_date_char end_date_char team_size planAM actualAM plan_duration_weeks actual_duration_weeks plan_duration_days actual_duration_days duration_variance_schedule_days duration_variance_schedule_percent plan_task_hours actual_task_hours

This provides all the necessary information about project size measured in several different ways. I also have some partially completed work on joining related projects, but that is beyond the scope of what we can address in a paper this short.

Is there anything else you need.

Plan/Actual AM are added and modified LOC

**Comment by WilliamNichols** [comment]
I don't think I hit the right button,  there, reopened.

**Comment by timm** [comment]
cant see it. email to me?

but before that: the real issue here, i think, is not "how big are the TSP projects" but "how big are the TSP projects relative to all projects". more generally , the issue we have to resolve is this:
- did we **NOT** see phase delay since all our project are too small? @WilliamNichols 

@llayman : how big were the prior projects were phase delay was reported?
@fshull : what can we say about the usual size of software projects?

**Comment by WilliamNichols** [comment]
OK, it is in my local, but must not have synced.

**Comment by WilliamNichols** [comment]
I think I pushed it this time. I should stick to the command line, I find the affordances of the GUI to be unintuitive. And Git seems designed to confuse someone coming from CVS or SVN

**Comment by timm** [comment]
@WilliamNichols 

so i multiplied 

team_size \* actual_duration_days

and got 

![image](https://cloud.githubusercontent.com/assets/29195/9283155/84d2b688-429f-11e5-991a-e0e1b663926f.png)

does that look right to you? median effort in your projects is about 300 stafff days?

**Comment by WilliamNichols** [comment]
Looks about right. A typical small project is 3-5 people for 2 or 3 months.  If it matters, calendar days were not discounted for weekends. I have that calculation but didn't put on that table.

A reality check ( and demonstration of noise) would compare total task hours.

Size is not terribly reliable, it is measured very differently by different projects. Effort in hours is very reliable. 2.5 to 3 effort hours is a typical man day equivalent

Sent from my iPhone

On Aug 14, 2015, at 4:16 PM, Tim Menzies <notifications@github.com<mailto:notifications@github.com>> wrote:

@WilliamNicholshttps://github.com/WilliamNichols

so i multiplied

team_size \* actual_duration_days

and got

[image]https://cloud.githubusercontent.com/assets/29195/9283189/c415a33c-429f-11e5-9aad-0a25feb4455f.png

does that look right to you? median effort in your projects is about 300 stafff days?

[image]https://cloud.githubusercontent.com/assets/29195/9283155/84d2b688-429f-11e5-991a-e0e1b663926f.png

**Comment by timm** [comment]
ok. added to file. we're done

![image](https://cloud.githubusercontent.com/assets/29195/9283922/5ff5658a-42a5-11e5-902c-8814ed8f3fb9.png)
