### ISSUE TITLE
need a proof read... when everything else is done

### ISSUE THREAD

**Issue by timm** [ai-se/phaseDelay#26]

**Comment by WilliamNichols** [comment]
I completed a first read for overall tone.   The overall tone is good and the argument seems tight. There remain a couple issues we may want to discuss. I need to find a reader in which I can markup the pdf.

First, some minor editorial items
I found two minor issues that I fixed on the sharelatex

1)      “couch” was misspelled, changed to “coach”

2)      A sentence “3% of the data had data that was not credible such as tasks listed in one day that took like than six hours.” Changed to “

3)      3% of the data had _values_ that were not credible such as tasks listed in one in one day that took more than six hours for a single developer

4)      I did not change but suggest changing “beg the question” to “raise the question”. The traditional “beg the question” refers to circular reasoning in which the consequent is assumed. Common vernacular today often uses the phrase interchangeably  with “raise the question”. My go-to source for all matters of linguistic style is Steven Pinker,  points out that  the American Heritage dictionary (no stickler for evolving use of the language) recommends avoiding the modern construction because it might suggest the author is unaware of the logical fallacy. Inasmuch as we are making a logical argument with claims, I recommend we replace with “raises the question”

My first reading of the TSP section did not cause me any heartburn, but I will go over it again and I will go over the individual change items.

Remaining issues,

1)      How complete are the data? I think we want to be stronger on the limits of the data scope. It is there, (we no evidence suggesting that the net effect of this concern over all our projects is non-zero )  but we really have no evidence one way or the other about

a)      Other organizational costs, such as processing field defect reports ( measured at 7 hours at 3 com)

b)      Unless the test team is part of the development organization using TSP, we do not include them (I have a draft of a project development patters paper you might be interested in refactoring)

2)      We may be able to dig out but have not analyzed the effect of schedule delays

3)      The  “common wisdom” might result from  amortizing the cost/defect across all phase costs,  in which case a zero defect product would have an infinite cost/defect in test.

4)      Larger systems are more difficult to debug. The source of a fault is often more difficult to identify from a symptom in test, this problem grows with system scale.

5)      Survivor bias, failed projects may not make it to the repository (unlikely, I am hard pressed to recall outright failures on our projects)

6)      Recall bias https://en.wikipedia.org/wiki/Recall_bias  may be partially responsible for the common wisdom . this is related to

7)      Extreme values , such as the mars climate orbiter, the loss of Arianne 5, delays in 787

8)      Missing a major requirement appears to be pretty rare in this data. Requirements errors can be small.

With that, we might also suggest that the developer facing issues appear to be somewhat minor. If these differ from the system costs, however, that might explain differing perspectives of developers and product owners.

It remains that the conclusion that there is no DIE effect could be wrong, but it should not be assumed. More specifically, the effect needs to be precisely defined, studied, and periodically revisited when the development process changes.
