### ISSUE TITLE
Figure 12 - Found and fixed?

### ISSUE THREAD

**Issue by llayman** [ai-se/phaseDelay#35]
Figure 12 - Found and fixed? Does this mean each defect appears twice in the figure? Could you separate them? The current figure is hard to penetrate.

**Comment by WilliamNichols** [comment]
No defects are counted and displayed only once.  Find and fix is a single activity for tracking purposes. Find is the act of locating the source of the defect in the product,  that is determining what must be changed. 

Action: this should be clarified in the text because others may suffer the same confusion
