### ISSUE TITLE
Please add an N column to Fig 13.

### ISSUE THREAD

**Issue by llayman** [ai-se/phaseDelay#42]
> I am troubled by Fig. 12, how many defects have in total been fixed in the same phase in which they have been found? What is the proportion from the initial 47,376 defect logs that are concerned in the statistics in Fig. 13?

**Comment by WilliamNichols** [comment]
I will review the table and address this question. By and large same phase defects should be secondary injections, primarily from test phases.

**Comment by timm** [comment]
looks like @WilliamNichols  is handling this one. so i am passing this to him

**Comment by WilliamNichols** [comment]
Most defects should be fixed in the phase in which they were found.  By definition, the "phase" continues until the work is done. Though confusing, phase is not a synonym for type of activity. Test may include some design, coding,  compiling, and so forth, but remains "test" until the defects discovered have been resolved or determined to be left for later.   That is not normally the same as the phase in which they were injected,

**Comment by timm** [comment]
Bill... does this address this issue? Or more specifically, what is the reply to the reviewer?
